services:
  legacy-nmdc-documentation:
    # Use the container image built from `legacy/nmdc-documentation/Dockerfile`.
    build:
      context: legacy/nmdc-documentation
      dockerfile: Dockerfile
    ports:
      - "50000:8000"
    volumes:
      - ./legacy/nmdc-documentation:/app

  legacy-workflow-documentation:
    # Use the container image built from `legacy/workflow-documentation/Dockerfile`.
    build:
      context: legacy/workflow-documentation
      dockerfile: Dockerfile
    ports:
      - "50001:8000"
    volumes:
      - ./legacy/workflow-documentation:/app

  main-website:
    image: nginx  # Docs: https://hub.docker.com/_/nginx
    depends_on:
      - legacy-nmdc-documentation
      - legacy-workflow-documentation
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./content:/usr/share/nginx/html
      - ./legacy/nmdc-documentation/_build/html:/usr/share/nginx/html/legacy/nmdc-documentation
      - ./legacy/workflow-documentation/_build/html:/usr/share/nginx/html/legacy/workflow-documentation
