services:
  legacy-nmdc-documentation:
    # Use the container image built from `legacy/nmdc-documentation/Dockerfile`.
    build:
      context: legacy/nmdc-documentation
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
    volumes:
      - ./legacy/nmdc-documentation:/app

  nmdc-documentation:
    # Use the container image built from `content/nmdc/Dockerfile`.
    build:
      context: content/nmdc
      dockerfile: Dockerfile
    ports:
      - "5002:8000"
    volumes:
      - ./content/nmdc:/app

  main-website:
    image: nginx  # Docs: https://hub.docker.com/_/nginx
    depends_on:
      - legacy-nmdc-documentation
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./content:/usr/share/nginx/html
