services:
  legacy-home-docs:
    # Use the container image built from `content/legacy_home/Dockerfile`.
    build:
      context: content/legacy_home
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
    volumes:
      - ./content/legacy_home/src:/app/src

  home-docs:
    # Use the container image built from `content/home/Dockerfile`.
    build:
      context: content/home
      dockerfile: Dockerfile
    ports:
      - "5002:8000"
    volumes:
      - ./content/home/src:/app/src

  runtime-docs:
    # Use the container image built from `pullers/runtime_docs/Dockerfile`.
    build:
      context: pullers/runtime_docs
      dockerfile: Dockerfile
    ports:
      - "5003:8000"

  workflow-documentation:
    # Use the container image built from `pullers/Dockerfile`.
    build:
      context: pullers/workflow_docs
      dockerfile: Dockerfile
    ports:
      - "5004:8000"

  main-website:
    image: nginx  # Docs: https://hub.docker.com/_/nginx
    restart: unless-stopped
    depends_on:
      - legacy-home-docs
      - home-docs
      - runtime-docs
      - workflow-documentation
    ports:
      - "5000:80"
    volumes:
      - ./.docker/dev.nginx.conf:/etc/nginx/nginx.conf:ro
